print('Please, enter the following information')

first_name = input('First name: ')
last_name = input('Last name: ')
email = input('Email address: ')
phone = input('Phone number: ')
job_title = input('Job title: ')
ID_number = input('ID Number: ')
hair = input('Hair color: ')
eyes = input('Eyes color: ')
month = input('Month: ')
training = input('Training: ')

print()
print('The ID Card is:\n')
print('-------------------------------------')
print(last_name.upper() + ', ' + first_name)
print(job_title.capitalize())
print('ID: ' + ID_number)
print()
print(email)
print(phone)
print()
print('Hair: {:15} Eyes: {:10}'.format(hair, eyes))
print('Month: {:15} Training: {:10}'.format(month, training))
print('-------------------------------------')
